### PR TITLE
[feature] Bump minimum Go version to 1.22

### PR DESCRIPTION
**Pull request by basman**
Go v1.22 provides the loopvar improvement. Time to take advantage of it by bumping the go.mod files.

### CODE REVIEW

**Comment by fako1024** [comment]
IMHO we don't need to break backwards-compatibility in order to use the feature, do we? Don't get me wrong, we will compile with 1.22 anyway, but forcing this on `go.mod` level already would artificially drop the support for anything below that (unnecessarily). Or am I missing something?

**Comment by basman** [comment]
> forcing this on `go.mod` level already would artificially drop the support for anything below that (unnecessarily). Or am I missing something?
Without bumping the version in go.mod even with a modern 1.22 compiler, it will behave as the elder versions and not provide loopvar protection.

**Comment by fako1024** [comment]
> Without bumping the version in go.mod even with a modern 1.22 compiler, it will behave as the elder versions and not provide loopvar protection.

I see. Well, in that case we should at least ensure that:

- slimcap uses 1.22 as well (I can look into that) since 50% of what goProbe does happens there
- All the Github actions / pipelines use 1.22 as well (to ensure this doesn't incur any unwanted side effects)

**Comment by fako1024** [comment]
Rejecting this one in favor of https://github.com/els0r/goProbe/pull/295 (sorry @basman - There were indeed some side effects that required additional changes, so I simply created a new PR)...

**Pull request closed without merging**
