### PR TITLE
[feature] Create PR naming rule (enforcement) GitHub action

### LINKED ISSUE #90: Improve CI / CD pipeline
With #59 we have a great basis for CI / CD already. However, there are a few things that could be improved:

- [x] Removal of dummy tag `v3.0.1`
- [x] Automatic upload of binaries only (as suggested [here](https://github.com/els0r/goProbe/pull/86#discussion_r1148030324))
- [x] Automatic generation of better release comment (there should be a way to create a list of all commits since the last release, a.k.a. CHANGELOG)
- [x] Build / upload of `rpm` packages (and binaries for Fedora / CentOS)
- [x] Cross-check if tags (bug/feature) can be used in action, otherwise enforce
- [x] Add PR naming rule action
- [x] Re-test CD / release and confirm correct output

### PR DESCRIPTION
**Pull request by fako1024**
Should enforce the rules defined in #90 .

Closes #90

### CODE REVIEW

**Comment by fako1024** [comment]
First attempt failed as expected (deliberately used an invalid PR title): https://github.com/els0r/goProbe/actions/runs/4741752915/jobs/8419213247?pr=112

**Comment by fako1024** [comment]
@els0r Should finally bring the CI / CD pipeline to a great starting point. PR title rule enforcement works perfectly, it even gets triggered automatically once you change the title, so no need to manually interact.

**Comment by els0r** [comment]
Very nice! Thanks again for getting this important part of the repo off the ground!

Cheers from San Fransisco

**Comment by fako1024** [comment]
> Very nice! Thanks again for getting this important part of the repo off the ground!
> 
> Cheers from San Fransisco
Awesome! When you have a minute, could you hit the `approve` button, then I'll do another round of release testing! TY and safe travels!

**Comment by fako1024** [comment]
@els0r And BTW, I've also added a first shot at building artifacts for Alpine in the last few commits to this PR. Unfortunately I can't build a full package (yet) due to a missing build action for Alpine. Maybe I'll add one myself in the future, but for now I'm happy if I can download working binaries for Alpine via a tarball...

**Review by els0r — APPROVED** [review]

**Pull request merged**
