### PR TITLE
[feature][doc] Cleanup some obsolete resources

### LINKED ISSUE #211: Cleanup a few obsolete repository resources
When going through the repo I found a few minor things that probably are not needed anymore:

- [x] https://github.com/els0r/goProbe/blob/main/sanity_checks.sh (unsure, seems like some outdated convenience script)
- [x] https://github.com/els0r/goProbe/blob/main/global-query (binary, shouldn't be there)
- [x] https://github.com/els0r/goProbe/blob/main/CHANGES (has been superseded by CD pipeline)
- [x] https://github.com/els0r/goProbe/tree/main/examples/lz4test (there's multiple unit and integration tests for this, IMHO we don't need an additional binary on top of that)
 ==> Adapt https://github.com/els0r/goProbe/blob/main/examples/README.md
- [x] https://github.com/els0r/goProbe/blob/main/addon/serialize_ipprot_list.sh (can / should be replaced by a `go generate` setup)
- [x] https://github.com/els0r/goProbe/blob/main/addon/Makefile (not needed anymore)
- [x] https://github.com/els0r/goProbe/blob/main/addon/goprobe.service (move to examples)
- [x] https://github.com/els0r/goProbe/blob/main/addon/goprobe.conf.example (outdated, examples present in `examples` folder)
- [x] https://github.com/els0r/goProbe/tree/main/addon/testdb (outdated / obsolete)
- [x] https://github.com/els0r/goProbe/tree/main/addon (will have nothing left)

### PR DESCRIPTION
**Pull request by fako1024**
@els0r This is a bit of tidying up obsolete resources and straightening out the IP protocol generation using a proper `go generate` setup. PTAL and let me know if there's anything in there that you have strong feelings about (for an overview of changes see the issue commen / TODOt: #211).

It would be great if you could run `go generate` in the `pkg/goDB/protocols` folder on you MacOS host to refresh / test the generator.

Closes #211

### CODE REVIEW

**Review by els0r — APPROVED** [review]
Cool! Not at laptop at the moment to cross-check the darwin part. This is okay though, since I can neither capture nor query traffic on darwin 🤗

**Comment by els0r** [comment]
One more note, the addon folder is explicitly mentioned in the goProbe docs. We should change that too

**Comment by fako1024** [comment]
> One more note, the addon folder is explicitly mentioned in the goProbe docs. We should change that too

Good catch, would have missed that. Also found that the examples are used in the package build pipeline, fixed that, too.

**Comment by fako1024** [comment]
@els0r FYI: I've also fixed the branch rules for the CodeQL action (was still restricted to `master`) and found a way to avoid running the Go pipeline twice every time there is a push on a PR (c.f. this: https://github.com/orgs/community/discussions/57827):
image

**Pull request merged**
