### PR TITLE
[bugfix] Filter out duplicates in protocols_generator and sort

### LINKED ISSUE #233: Fix: protocols generator should be aware of duplicates and filter them out
Observed on a target system:

```
+       253: "Use",
+       254: "Use",
        255: "UNKNOWN",
```
This will lead to the compiler complain about duplicate keys.

**DoD:**

- [ ] adjust https://github.com/els0r/goProbe/blob/main/pkg/goDB/protocols/protocols_generator.go to filter out duplicates
- [ ] sort by name for the `map[string]int` map (readability play)

### PR DESCRIPTION
**Pull request by els0r**
There were cases on some linux systems where two different indexes had the same protocol "Use". Also, darwin has protocols at 258, which would effectively break conversion to `uint8`.

This commit addresses both of these issues and adds some sorting of the `map[string]int` on top.

Closes #233

### CODE REVIEW

**Review by fako1024 — APPROVED** [review]
@els0r For now let's do it this way, but could you maybe open a new issue for us to review the `proto` concept? If we're having this much potential for mismatches / conflicts maybe we should rethink our strategy (and e.g. just create _one_ set from a Linux system using the Linux generator and _use_ that for all systems - after all this is just naming, and I don't see any reason why we really have to differentiate protocol naming across architectures).

**Review by fako1024 — CHANGES_REQUESTED** [review]
Sorry to go forth and back on this. Just realized this is simply a bug, not a duplication:
```
#   253     Use for experimentation and testing           [RFC3692]
#   254     Use for experimentation and testing           [RFC3692]
```
-> It's basically unused. The splitter just messes up with the text from what I can see.

**Comment by els0r** [comment]
> Sorry to go forth and back on this. Just realized this is simply a bug, not a duplication:
> 
> ```
> #   253     Use for experimentation and testing           [RFC3692]
> #   254     Use for experimentation and testing           [RFC3692]
> ```
> 
> -> It's basically unused. The splitter just messes up with the text from what I can see.
> 
> Instead of the dedup (which simply shouldn't be required) we should probably limit ourselves to the indexes up to 252 and that way avoid all the issues (or skip commented lines)?

Sure. Honestly no reason to block this PR (because it blocks the other one too). But hey, here we are.

**Comment by els0r** [comment]
> @els0r For now let's do it this way, but could you maybe open a new issue for us to review the `proto` concept? If we're having this much potential for mismatches / conflicts maybe we should rethink our strategy (and e.g. just create _one_ set from a Linux system using the Linux generator and _use_ that for all systems - after all this is just naming, and I don't see any reason why we really have to differentiate protocol naming across architectures).

Can we park this? I don't want to explain to people at Open Systems why the protocols all of a sudden are differently named.

**Review by fako1024 — APPROVED** [review]

**Comment by fako1024** [comment]
> > Sorry to go forth and back on this. Just realized this is simply a bug, not a duplication:
> > ```
> > #   253     Use for experimentation and testing           [RFC3692]
> > #   254     Use for experimentation and testing           [RFC3692]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > -> It's basically unused. The splitter just messes up with the text from what I can see.
> > Instead of the dedup (which simply shouldn't be required) we should probably limit ourselves to the indexes up to 252 and that way avoid all the issues (or skip commented lines)?
> 
> Sure. Honestly no reason to block this PR (because it blocks the other one too). But hey, here we are.

Fair, sorry for the blocker...

**Comment by fako1024** [comment]
> > @els0r For now let's do it this way, but could you maybe open a new issue for us to review the `proto` concept? If we're having this much potential for mismatches / conflicts maybe we should rethink our strategy (and e.g. just create _one_ set from a Linux system using the Linux generator and _use_ that for all systems - after all this is just naming, and I don't see any reason why we really have to differentiate protocol naming across architectures).
> 
> Can we park this? I don't want to explain to people at Open Systems why the protocols all of a sudden are differently named.

Absolutely, we should just make sure we don't forget (because IMHO this is a low hanging fruit). And just to make sure we're on the same page: Nobody would / will have to explain anything to anyone because nothing would change on Linux. I'm merely proposing to generate _one_ global list on Linux (probably once a decade, because I doubt there's going to be a lot of changes to these protocols) and use that on all architectures. After all, protocols are global and in principle independent of OS, except maybe for some minor naming differences (if they weren't, the internet would have a problem I guess) and some Apple / Windows internals (which we probably won't care about because they won't really show up in a global traffic monitoring).

**Comment by els0r** [comment]
> > > @els0r For now let's do it this way, but could you maybe open a new issue for us to review the `proto` concept? If we're having this much potential for mismatches / conflicts maybe we should rethink our strategy (and e.g. just create _one_ set from a Linux system using the Linux generator and _use_ that for all systems - after all this is just naming, and I don't see any reason why we really have to differentiate protocol naming across architectures).
> 
> > 
> 
> > Can we park this? I don't want to explain to people at Open Systems why the protocols all of a sudden are differently named.
> 
> 
> 
> Absolutely, we should just make sure we don't forget (because IMHO this is a low hanging fruit). And just to make sure we're on the same page: Nobody would / will have to explain anything to anyone because nothing would change on Linux. I'm merely proposing to generate _one_ global list on Linux (probably once a decade, because I doubt there's going to be a lot of changes to these protocols) and use that on all architectures. After all, protocols are global / based on RFCs and in principle independent of OS, except maybe for some minor naming differences (if they weren't, the internet would have a problem I guess) and some Apple / Windows internals (which we probably won't care about because they won't really show up in a global traffic monitoring).

Sounds good. Where I was coming from: I recall seeing the protocols from the shipped _linux.go be different than the _linux.go on OSIX. But I would have to double check that again.

Apple/Windows is different for sure. But we don't really care ;)

**Pull request merged**
