### PR TITLE
[feature] Improve legacy tool concurrency and add support for profiling / PGO

### LINKED ISSUE #148: Increase legacy conversion tool throughput
In order to maximize convenience when migrating to v4 the legacy conversion tool should be as fast a possible. Using conversion parallelization should improve performance substantially.

DoD

- [x] Review conversion tool
- [x] Implement proper fan-in / fan-out for read / convert / write operations
- [x] Have @els0r test on large production database host (find largest DB on sensor fleet)

### PR DESCRIPTION
**Pull request by fako1024**
Changes implemented (fan-in / fan-out was actually already in place quite properly):

- [x] Improved concurrency to use half of available cores by default (override to any static number possible)
- [x] Capture profile and enabled PGO

@els0r I'll keep it a draft for now - could you maybe compile the tool from this branch (using `-pgo=auto`) and then run it with default options (should use half of all cores as discussed) on your most favorite DB for comparison?

Closes #148

### CODE REVIEW

**Comment by els0r** [comment]
@fako1024 : thanks for the first round with this PR. I did find a 51G DB on a host. It's by far the largest one I've seen out there (currently running an exhaustive listing on DB size) .Using the version from this branch conversion came out as follows:
```
real	10m0.614s
user	41m2.637s
sys	8m42.968s
```

**Comment by fako1024** [comment]
@els0r Thanks for checking it out so quickly (and the feedback of course). I really like the idea of limiting the time frame for very large DBs, and if you say with the speedup _plus_ that you're confident to perform the migration I'm of course on board.

Alternatively, if you want to squeeze out the last drop, maybe draw a profile (that version has a `profile` flag to write a CPU profile during writeout) on the huge DB and forward it to me (on second thought that might be a cool idea anyway because I could use that as default input for PGO :stuck_out_tongue:) and I'll have a closer look where there might be additional bottlenecks (in particular on the hardware we're talking about)...

**Comment by els0r** [comment]
@fako1024 : I don't know why I didn't do it in the first place. Will send over later today :)

**Comment by fako1024** [comment]
@els0r Alright, updated the PGO file with your profile. Looking at it I don't see any obvious bottleneck that we could easily resolve without significant effort TBH.
However, I've added the `-l` option to the `legacy` tool so a custom compressor level can be set for the bulk operation. That way it might be possible to speed up the process by sacrificing a few percent off the compressed DB size (which will be cycled out over time and be replaced with default compression level data OR can be recompressed to optimal level asynchronously post-update).

A few caveats / details though:

- It may be that anything other than using `-l 1` will not speed up the process (Any level between [2,5] produced worse results at slower speed on my test DB) due to the way the leveling works for LZ4 (TL;DR: It's not guaranteed that speed / compressibility follows the level linearly, highly dependent on the data). You might have to try on a production level DB to figure out if there's a useful sweet spot (no idea how much you'll lose in terms of compressibility for level 1).
- Given you reporting that conversion ran at >90% I/O it might be that there's really not much to improve here anyway because you're already (almost) limited by I/O (and I'm not sure it's a good idea to exhaust that metric for a few minutes as it may have detrimental effects on all other services on that host, including routing).
- When implementing this I realized that we actually completely ignored any setting of compressor (even type) for the `DBWriter` (must have slipped through), it would always just use `LZ4`. I fixed that as part of this PR.

Maybe do another test and play with the compression level and then give me a final thumbs up / down if this is OK for you / OSAG...

**Comment by els0r** [comment]
> Maybe do another test and play with the compression level and then give me a final thumbs up / down if this is OK for you / OSAG...

Thanks a lot for the update. And the additional level. Given the fact that the largest DB out there is 109G, I know that we have to do the pruning one way or the other. I would also like to have the space savings straight off the bat.

So from my end: all good! And thank you for revisiting this.

**Pull request merged**
